### ISSUE TITLE
Comments: `Contents::injectComments()` hangs when a comment does not follow its sibling lines indentation level

### ISSUE THREAD

**Issue by yannoff** [yannoff/y-a-m-l#7]
## Problem

Given the following source YAML:

```yaml
level1:
    level2:
# this is the problematic comment
        level3:
        ...
```

The `Contents::injectComments()` call hangs and never terminate. 

## Reason

When a comment does not follow its sibling lines indentation level, the `Contents::getParentYpath()` mistakenly interpret the first encountered upper comment as the parent level line, whereas it should not.

Hence the calculated `YPath` for the `level3` line is `.level3` while it should be `level1.level2.level3`
